### ISSUE TITLE
Rebuild DockerHub image for Rust 1.47+

### ISSUE THREAD

**Issue by jamesmcm** [ebbflow-io/cargo-rpm-amd64-opensuseleap#1]
Hi,

Could you please rebuild the DockerHub image - https://hub.docker.com/r/ebbflow/cargo-rpm-amd64-opensuseleap/tags?page=1&ordering=last_updated

To include a newer version of Rust, as my Github actions are failing now that some dependencies are using more recently stabilised features.

Looking at the script I don't think anything needs to change, it literally just needs to be re-built and uploaded.

**Comment by gorup** [comment]
Apologies for my delay, I've changed jobs and such so I've been busy and haven't been on Github in a while. I just released a new version, 1.50.0. Thx!
